# -*- coding: utf-8 -*-
"""KalkulatorSederhana.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1dJTMHwj8-ZZirXTRiGN1BQvb2Dt8LEYO
"""

# Kalkulator sederhana

# Fungsi untuk menambahkan dua bilangan
def tambah(x, y):
   return x + y

# Fungsi untuk mengurangi dua bilangan
def kurang(x, y):
   return x - y

# Fungsi untuk memperkalian dua bilangan
def kali(x, y):
   return x * y

# Fungsi untuk membagi dua bilangan
def bagi(x, y):
   return x / y

print("Pilih operasi.")
print("1.Tambah")
print("2.Kurang")
print("3.Kali")
print("4.Bagi")

# Meminta input dari user
pilihan = input("Masukkan pilihan(1/2/3/4): ")

bilangan1 = int(input("Masukkan bilangan pertama: "))
bilangan2 = int(input("Masukkan bilangan kedua: "))

if pilihan == '1':
   print(bilangan1,"+",bilangan2,"=", tambah(bilangan1,bilangan2))

elif pilihan == '2':
   print(bilangan1,"-",bilangan2,"=", kurang(bilangan1,bilangan2))

elif pilihan == '3':
   print(bilangan1,"*",bilangan2,"=", kali(bilangan1,bilangan2))

elif pilihan == '4':
   print(bilangan1,"/",bilangan2,"=", bagi(bilangan1,bilangan2))
else:
   print("Input salah")